<html>
<head>
<title>PayPal Plus Payments</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php 
$startPageTime=microtime(TRUE);
if ($DISPLAY == "paywall" ) { 
	#echo '<script src="https://www.paypalobjects.com/webstatic/ppplus/ppplus.min.js" type="text/javascript"></script>';
	echo '<script src="js/ppplus.min.js" type="text/javascript"></script>';
} 
?>
</head><body><center>

<h1>PayPal Plus T-Shirt Shop</h1>
<hr></center>

